cakecravings/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('profiles/', include('profiles.urls')),
]
handler404 = 'cakecravings.views.handler404'
handler500 = 'cakecravings.views.handler500'

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('get_cart_count/', views.get_cart_count, name='get_cart_count'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update_delivery_option/', views.update_delivery_option, name='update_delivery_option'),
]

wishlist/urls.py
from django.urls import path
from .views import view_wishlist, plus_wishlist, minus_wishlist, wishlist_delete

app_name = 'wishlist'

urlpatterns = [
    path('', view_wishlist, name='view_wishlist'),
    path('pluswishlist/', plus_wishlist, name='pluswishlist'),
    path('minuswishlist/', minus_wishlist, name='minuswishlist'),
    path('delete/<int:product_id>/', wishlist_delete, name='wishlist_delete'),
]

wishlist/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


class Wishlist(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='wishlist'
    )
    products = models.ManyToManyField(
        Product,
        blank=True,
        related_name='wishlists'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Wishlist'
        verbose_name_plural = 'Wishlists'

    def __str__(self):
        return str(self.user) + '\'s wishlist'

    def add_to_wishlist(self, product):
        if product not in self.products.all():
            self.products.add(product)
            return True
        return False

    def remove_from_wishlist(self, product):
        if product in self.products.all():
            self.products.remove(product)
            return True
        return False

    def remove_all_from_wishlist(self):
        self.products.clear()
        return True

    def get_products(self):
        return self.products.all()

wishlist/views.py
from django.views import View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from .models import Wishlist
from products.models import Product
from django.core import serializers
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.urls import reverse
from django.contrib import messages


def view_wishlist(request):
    user = request.user
    if user.is_authenticated:
        wishlist, created = Wishlist.objects.get_or_create(user=user)
        wishlist_products = wishlist.products.all()
    else:
        wishlist_products = []

    context = {
        'wishlist_products': wishlist_products,
    }

    return render(request, 'wishlist/wishlist.html', context)


@login_required
def plus_wishlist(request):
    if request.method == 'GET':
        prod_id = request.GET.get('prod_id')
        product = get_object_or_404(Product, id=prod_id)
        user = request.user

        wishlist, created = Wishlist.objects.get_or_create(user=user)
        wishlist.add_to_wishlist(product)

        # Add a success message
        messages.success(request, 'Product added to wishlist successfully.')

        # Get the URL for the product detail page
        product_url = reverse('product_detail', args=[prod_id])

        # Return the URL in the JSON response
        data = {
            'success': True,
            'redirect_url': product_url,
        }
        return JsonResponse(data)


@login_required
def minus_wishlist(request):
    if request.method == 'GET':
        prod_id = request.GET['prod_id']
        product = Product.objects.get(id=prod_id)
        user = request.user

        wishlist, created = Wishlist.objects.get_or_create(user=user)
        removed = wishlist.remove_from_wishlist(product)

        # Get the URL for the product detail page
        product_url = reverse('product_detail', args=[prod_id])

        # Return the URL in the JSON response
        data = {
            'message': 'Wishlist Remove Successfully',
            'removed': removed,
            'redirect_url': product_url,
        }
        return JsonResponse(data)


def wishlist_delete(request, product_id):
    user = request.user
    if user.is_authenticated:
        wishlist, created = Wishlist.objects.get_or_create(user=user)
        product = get_object_or_404(Product, id=product_id)
        wishlist.products.remove(product)

    return redirect('wishlist:view_wishlist')

wishlist/templates/wishlist/wishlist-list.html
{% extends "base.html" %}
{% load static %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Wishlist{% endblock %}

{% block content %}
<!-- core/async/wishlist-list.html -->

{% if wishlist %}
<ul>
    {% for product in wishlist %}
    <li>
        <span>{{ product.name }}</span>
        <button style="border: none;" data-wishlist-product="{{ product.id }}"
            class="text-body delete-wishlist-product">
            <i class="fi-rs-trash"></i>
        </button>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Your wishlist is empty.</p>
{% endif %}
<script>
    $(document).on("click", ".delete-wishlist-product", function () {
        let this_val = $(this);
        let product_id = $(this).attr("data-wishlist-product");

        $.ajax({
            url: "/remove-from-wishlist/",
            data: {
                product_id: product_id
            },
            dataType: "json",
            beforeSend: function () {
                console.log("Removing from wishlist...");
            },
            success: function (res) {
                $("#wishlist-list").html(res.data);
            }
        });
    });
</script>


{% endblock %}

wishlist/templates/wishlist/wishlist.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5 mb-5" style="min-height: 100px;">
    {% if wishlist_products %}
    <h1 class="mb-4">Your Wishlist</h1>
    <div class="row">
        {% for product in wishlist_products %}
        <div class="col-md-4 mb-4">
            <a href="{% url 'product_detail' product.id %}" class="card-link wishlist-link">
                <div class="card">
                    {% if product.images.all %}
                    <img src="{{ product.images.first.image.url }}" alt="{{ product.name }}" class="card-img-top"
                        style="object-fit: contain;">
                    {% else %}
                    <!-- Display a default image if no product image is available -->
                    <img src="{% static 'images/default_image.png' %}" alt="{{ product.name }}"
                        class="card-img-top" style="object-fit: contain;">
                    {% endif %}
                    <div class="card-body">
                        <h3 class="card-title" style="font-size: 1.5rem;">{{ product.name }}</h3>
                        <h6 class="card-text" style="font-size: 1.2rem;">€{{ product.price }}</h6>
                        <form method="POST" action="{% url 'wishlist:wishlist_delete' product.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm wishlist-button">Remove</button>
                        </form>
                        
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>Your wishlist is empty.</p>
    <a href="{% url 'all_products' %}" class="btn btn-outline-secondary">
        <span class="icon">
            <i class="fa-regular fa-circle-left"></i>
        </span>
        <span>Back to Menus</span>
    </a>
    {% endif %}
</div>
<style>
    .mt-5, .my-5 {
    margin-top: 7rem!important;
}

/* Style for the wishlist button */
.wishlist-button {
    width: 100px; 
    height: 40px; /* Adjust the height as needed */
}
</style>

{% endblock %}