cakecravings/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('profiles/', include('profiles.urls')),
]
handler404 = 'cakecravings.views.handler404'
handler500 = 'cakecravings.views.handler500'

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('get_cart_count/', views.get_cart_count, name='get_cart_count'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update_delivery_option/', views.update_delivery_option, name='update_delivery_option'),
]

orders/urls.py
from django.urls import path
from .views import AddOrder, basket_view, OrderConfirmation, OrdersView, OrderDetailsView, stripe_webhook, ErrorView,OrderListView, OrderStatusUpdateView


app_name = 'orders'

urlpatterns = [
    path('add_order/', AddOrder.as_view(), name='add_order'),
    path('basket_view/', basket_view, name='basket_view'),
    path('error/', ErrorView.as_view(), name='error'),
    path('order_confirmation/', OrderConfirmation.as_view(), name='order_confirmation'),
    path('user_orders/', OrdersView.as_view(), name='user_orders'),
    path('order_details/<str:order_number>/', OrderDetailsView.as_view(), name='order_details'), 
    path('stripe_webhook/', stripe_webhook, name='stripe_webhook'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:order_id>/update-status/', OrderStatusUpdateView.as_view(), name='order-status-update'),


]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from django.db.models import Sum
from django.conf import settings
from shortuuid.django_fields import ShortUUIDField
from decimal import Decimal
from django.db.models import Sum, F, ExpressionWrapper, DecimalField

class Order(models.Model):
    PENDING = 'Pending'
    PROCESSING = 'Processing'
    SHIPPED = 'Shipped'
    DELIVERED = 'Delivered'
    READY_FOR_PICKUP = 'Ready For Pickup'

    STATUS_CHOICES = (
        (PENDING, 'Pending'),
        (PROCESSING, 'Processing'),
        (SHIPPED, 'Shipped'),
        (DELIVERED, 'Delivered'),
        (READY_FOR_PICKUP, 'Ready For Pickup'),
    )
    GERMAN_STATES_CHOICES = (
        ('BW', 'Baden-Württemberg'),
        ('BY', 'Bavaria (Bayern)'),
        ('BE', 'Berlin'),
        ('BB', 'Brandenburg'),
        ('HB', 'Bremen'),
        ('HH', 'Hamburg'),
        ('HE', 'Hesse (Hessen)'),
        ('NI', 'Lower Saxony (Niedersachsen)'),
        ('MV', 'Mecklenburg-Western Pomerania (Mecklenburg-Vorpommern)'),
        ('NW', 'North Rhine-Westphalia (Nordrhein-Westfalen)'),
        ('RP', 'Rhineland-Palatinate (Rheinland-Pfalz)'),
        ('SL', 'Saarland'),
        ('SN', 'Saxony (Sachsen)'),
        ('ST', 'Saxony-Anhalt (Sachsen-Anhalt)'),
        ('SH', 'Schleswig-Holstein'),
        ('TH', 'Thuringia (Thüringen)'),
    )

    DELIVERY_OPTIONS = (
        ('online', 'Online Delivery'),
        ('pickup', 'Pickup'),
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='order_user'
    )
    full_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=100, blank=True)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(
        max_length=100,
        choices=GERMAN_STATES_CHOICES,
        blank=True, 
        null=True,
    )
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_paid = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    order_id = ShortUUIDField(
        unique=True,
        max_length=30,
        prefix='cc',
        alphabet='abcdefgh12345'
    )
    order_key = models.CharField(max_length=200, blank=True, null=True)
    billing_status = models.BooleanField(default=False)
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default=PENDING
    )
    delivery_option = models.CharField(
        max_length=10,
        choices=DELIVERY_OPTIONS,
        default='online',
    )
    order_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    delivery_cost = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"Order ID: {self.order_id}, Order Number: {self.order_key}, Order Total: ${self.order_total}"

    def get_order_items(self):
        items = OrderItem.objects.filter(order=self)
        return items
    
    def update_total(self):
        """
        Update order total, delivery cost, and grand total.
        """
        # Calculate the order total by iterating through related OrderItem objects
        order_items = self.order_item.all()
        order_total = 0  # Initialize order_total

        for item in order_items:
            item_total = item.get_total()

            # If the item has a size, consider it for the order total calculation
            if item.size and item.size != 'None':
                order_total += item_total

        # Use 0 if the order total is None
        self.order_total = order_total if order_total is not None else Decimal('0.00')

        # Calculate the delivery cost separately
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD and self.delivery_option == 'online':
            self.delivery_cost = self.order_total * (settings.STANDARD_DELIVERY_PERCENTAGE / Decimal('100.0'))
        else:
            self.delivery_cost = Decimal('0.00')

        # Calculate the grand total by adding order total and delivery cost
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

class OrderItem(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_item')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=5, choices=Product.SIZE_CHOICES, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)  # Specify a default value

    def __str__(self):
        return f"{self.quantity} x {self.product.name}" + (f" ({self.size})" if self.size else "")

    def get_total(self):
        return self.quantity * self.price  # Use the price field for the calculation

orders/views.py
import json
import stripe
import uuid
import logging
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
from django.contrib.auth.mixins import LoginRequiredMixin
from cart.contexts import cart_contents
from orders.models import Order, OrderItem
from products.models import Product
from profiles.models import Profile
from reviews.models import Review
from decimal import Decimal
from .forms import OrderForm


# Set up the logger
logger = logging.getLogger(__name__)


class AddOrder(View):
    """View for adding order AJAX."""
    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                cart = cart_contents(request)
                total = cart['grand_total']
                delivery_option = request.POST.get('delivery_option', 'online')  # Get the delivery option
                
                # Debug statement
                print(f"Delivery Option (AddOrder - Received from Cart): {delivery_option}")

                # Create PaymentIntent
                try:
                    intent = stripe.PaymentIntent.create(
                        amount=int(total * 100),  # Convert to cents
                        currency='eur',
                        metadata={'userid': request.user.id, 'delivery_option': delivery_option}
                    )
                except stripe.error.CardError as e:
                    # Handle card error
                    return JsonResponse({'success': False, 'message': str(e)})

                # Retrieve delivery_option from metadata
                print(request.POST)
                delivery_option = request.POST.get('delivery_option', 'online')
                print(f"Delivery Option (AddOrder - After PaymentIntent): {delivery_option}")

                user = request.user
                full_name = request.POST.get('full_name')
                email = request.POST.get('email')
                phone = request.POST.get('phone')
                address1 = request.POST.get('address1')
                address2 = request.POST.get('address2')
                country = request.POST.get('country')
                
                # Debug statement
                state = request.POST.get('state')
                print(f"State (AddOrder): {state}")

                city = request.POST.get('city')
                zip_code = request.POST.get('zip_code')
                order_key = request.POST.get('order_key')

                # Calculate the total amount without delivery cost
                total_amount = cart['total']

                # Calculate the delivery cost separately
                delivery_cost = total - total_amount

                # Determine the delivery option
                delivery_option = request.POST.get('delivery_option', 'online')

                # Include delivery cost in total_paid for online delivery
                if delivery_option == 'online':
                    total_paid = str(total_amount + delivery_cost)
                else:
                    total_paid = str(total_amount)

                cart_items = cart['cart_items']

                if Order.objects.filter(order_key=order_key).exists():
                    return JsonResponse({'success': False, 'message': 'Order with the same key already exists.'})
                else:
                    order = Order.objects.create(
                        user=user,
                        full_name=full_name,
                        email=email,
                        phone=phone,
                        address1=address1,
                        address2=address2,
                        country=country,
                        state=state,
                        city=city,
                        zip_code=zip_code,
                        order_key=order_key,
                        total_paid=total_paid,
                        delivery_option=delivery_option,  # Set the delivery option
                    )
                    for cart_item in cart_items:
                        # Assuming 'product', 'quantity', and 'size' are keys in your cart item
                        product = cart_item['product']
                        quantity = cart_item['quantity']
                        selected_size = cart_item.get('size', 'S')  # Replace 'S' with the default size if not present

                        # Get the price for the selected size
                        price_for_size = product.get_discounted_price_for_size(selected_size)

                        OrderItem.objects.create(
                            order=order,
                            product=product,
                            quantity=quantity,
                            size=selected_size,
                            price=price_for_size,  # Set the price for the selected size
                        )

                    # Update the order total, delivery cost, and grand total
                    order.update_total()

                    # Set billing status to True since the payment is successful
                    order.billing_status = True
                    order.save()

                    # Send confirmation email
                    send_payment_confirmation_email(order.email, order_key, total_paid)

                    # Clear the cart only if the payment was successful
                    request.session['cart'] = {}
                    return JsonResponse({'success': True, 'message': 'Order added successfully'})
            return JsonResponse({'success': False, 'message': 'Invalid request'})
        else:
            return render(request, 'account/login.html')


@login_required
def basket_view(request):
    try:
        # Attempt to get the latest order for the user
        try:
            latest_order = Order.objects.filter(user=request.user).latest('created')
        except Order.DoesNotExist:
            # If the order doesn't exist, create a new one
            latest_order = Order.objects.create(user=request.user)

        # Inside the basket_view function
        delivery_option = request.GET.get('delivery_option', 'online')

        # Fetch other cart details from cart_contents
        cart = cart_contents(request)
  

        # Update the cart with the latest delivery option
        cart['delivery_option'] = delivery_option

        # Initialize my_profile and primary_address
        my_profile = None
        primary_address = None

        # Check if the user has a profile
        try:
            my_profile = Profile.objects.get(user=request.user)
            primary_address = my_profile if my_profile.is_primary_address else None
        except Profile.DoesNotExist:
            pass

        # Check if the delivery option is 'pickup' and adjust the total accordingly
        if 'delivery_option' in cart and cart['delivery_option'] == 'pickup':
            total_final = cart.get('total', 0)  # Use the total without delivery cost for 'pickup'
            delivery_cost = 0  # Set delivery cost to 0 for 'pickup'
        else:
            total_final = cart.get('grand_total', 0)  # Use the grand total for 'online'
            delivery_cost = cart.get('delivery', 0)  # Include delivery cost for 'online'

        # Apply any discount logic here
        discount_amount = cart.get('discount', 0)
        total_final -= discount_amount

        total_sum = "{:.2f}".format(total_final)
        total = int(total_final * 100)
        stripe_public_key = settings.STRIPE_PUBLIC_KEY
        stripe.api_key = settings.STRIPE_SECRET_KEY

        intent = stripe.PaymentIntent.create(
            amount=total,
            currency='eur',
            metadata={'userid': request.user.id, 'delivery_option': delivery_option}
        )

        # Fetch user information from the latest order
        user_info = {
            'full_name': latest_order.full_name,
            'email': latest_order.email,
            'phone': latest_order.phone,
            'address1': latest_order.address1,
            'address2': latest_order.address2,
            'country': latest_order.country,
            'state': latest_order.state,
            'city': latest_order.city,
            'zip_code': latest_order.zip_code,
        }

        context = {
            'my_profile': my_profile,
            'primary_address': primary_address,
            'user_info': user_info,
            'total_sum': total_sum,
            'delivery_cost': delivery_cost,
            'delivery_option': delivery_option,  # Use the variable directly
            'client_secret': intent.client_secret,
            'stripe_public_key': stripe_public_key,
            'form': OrderForm(),
            'discount_amount': discount_amount,  # Include discount amount in context
        }

        return render(request, 'orders/payment.html', context)
    except Exception as e:
        logger.error(f"An error occurred in basket_view: {str(e)}")
        return HttpResponse("An error occurred.")


class OrderConfirmation(View):
    """View for the order placed page."""
    def get(self, request, *args, **kwargs):
        return render(request, 'orders/order_confirmation.html')


class OrdersView(View):
    """View for user orders page."""
    def get(self, request, *args, **kwargs):

orders/templates/orders/order_confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block extra_title %}Order Placed{% endblock %}

{% block content %}
<style>
    .order {
        margin-top: 150px;
        margin-bottom: 150px;
    }

    .row {
        justify-content: center;
        margin-top: 30px;
    }

    .card {
        border: none;
        text-align: center;
        border-radius: 20px;
        box-shadow: 0 4px 8px rgba(8, 1, 1, 0.1);
    }

    .title {
        font-size: 45px;
        margin-bottom: 35px;
    }

    .card-text {
        color: #242425;
        font-size: 20px;
    }

    .mt-5 {
        margin-top: 5rem;
    }

    .mb-4 {
        margin-bottom: 4rem;
    }

    .btn-primary {
        background-color: #3c1e49;
        border-color: #3c1e49;
        font-weight: bold;
    }

    .btn-primary:hover {
        background-color: #4a2858;
        border-color: #4a2858;
    }
</style>

<div class="order mt-6">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card p-4">
                <h2 class="title"> Order Placed Successfully</h2>
                <h4>Your order has been placed successfully. An email confirmation has been sent to you. </h4>

                <!-- You can add more details about the order here if needed -->

                <div class="mt-4">
                    {% with user=request.user %}
                    <a href="{% url 'orders:user_orders' %}" class="btn btn-primary">
                        <i class="fas fa-shopping-cart"> View Orders</i>
                    </a>
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/order_details.html
{% extends 'base.html' %}

{% block extra_title %}Order Details{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Order Details</h1>
    <div class="card mb-4">
        <div class="card-header">
            <strong>Order ID:</strong> {{ order.order_id }}
        </div>
        <div class="card-body">
            <h5 class="card-title">Order Number: {{ order.order_key }}</h5>
            <p class="card-text">
                <strong>Order Date:</strong> {{ order.created }}<br>
                <strong>Order Total:</strong> {{ order.total_paid }}<br>
                <strong>Status:</strong> <span class="status {{ order.status|lower }}">{{ order.status }}</span><br>
                <strong>Delivery Option:</strong> {{ order.get_delivery_option_display }}
            </p>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <h3>Order Items</h3>
        </div>
        <div class="card-body">
            <ul>
                {% for item in order_items %}
                <li class="mb-3">
                    <img src="{{ item.product.images.first.image_url }}" alt="{{ item.product.name }}" width="100" height="100" class="mr-3">
                    <div>
                        <p><strong>{{ item.quantity }} x {{ item.product.name }}</strong></p>
                        <p>{{ item.get_total }}</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <h3>Delivery Address</h3>
        </div>
        <div class="card-body">
            <p>
                <strong>Full Name:</strong> {{ order.full_name }}<br>
                <strong>Email:</strong> {{ order.email }}<br>
                <strong>Phone:</strong> {{ order.phone }}<br>
                <strong>Address:</strong> {{ order.address1 }}<br>
                {% if order.address2 %}<strong>Address 2:</strong> {{ order.address2 }}<br>{% endif %}
                <strong>City:</strong> {{ order.city }}<br>
                <strong>State:</strong> {{ order.county_region_state }}<br>
                <strong>Country:</strong> {{ order.country }}<br>
                <strong>Zip Code:</strong> {{ order.zip_code }}<br>
            </p>
        </div>
    </div>
</div>
<style>
    /* Add this to your CSS file or style section */
.status {
    font-weight: bold;
}

.status.pending {
    color: orange; /* Set your preferred color for the "Pending" status */
}

.status.processing {
    color: blue; /* Set your preferred color for the "Processing" status */
}

.status.shipped {
    color: green; /* Set your preferred color for the "Shipped" status */
}

.status.delivered {
    color: #008000; /* Set your preferred color for the "Delivered" status */
}

.status.ready-for-pickup {
    color: #663399; /* Set your preferred color for the "Ready For Pickup" status */
}

</style>
{% endblock %}

orders/templates/orders/order_error.html
{% extends 'base.html' %}

{% block extra_title %}Error{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Error</h1>
    <p>An unexpected error occurred during payment confirmation.</p>
    
    <p>
        <a href="{% url 'orders:basket_view' %}">Retry payment</a>
    </p>
</div>
{% endblock %}

orders/templates/orders/order_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>All Orders</h1>
  <table>
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Full Name</th>
        <th>Email</th>
        <th>Status</th>
        <th>Delivery Option</th>
        <th>Created</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
        <tr>
          <td>{{ order.order_id }}</td>
          <td>{{ order.full_name }}</td>
          <td>{{ order.email }}</td>
          <td>{{ order.status }}</td>
          <td>{{ order.get_delivery_option_display }}</td>
          <td>{{ order.created }}</td>
          <td>
            <!-- No need for the delivery option dropdown in the form -->
            <form method="post" action="{% url 'orders:order-status-update' order_id=order.id %}">
              {% csrf_token %}
              <select name="new_status">
                {% for choice in order.STATUS_CHOICES %}
                  <option value="{{ choice.0 }}" {% if choice.0 == order.status %}selected{% endif %}>{{ choice.1 }}</option>
                {% endfor %}
              </select>
              <button type="submit">Update Status</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

orders/templates/orders/order_placed.html
{% extends 'base.html' %}
{% load static %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Order Placed{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card p-4">
                <h1 class="mb-4">Order Placed Successfully</h1>
                <p>Your order has been placed successfully. An email confirmation has been sent to you.</p>

                <!-- You can add more details about the order here if needed -->

                <div class="mt-4">
                    {% with user=request.user %}
                    <a href="{% url 'orders:user_orders' %}" class="btn btn-primary">
                        <i class="fas fa-shopping-cart"></i> View My Orders
                    </a>
                    {% endwith %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/user_orders.html
{% extends 'base.html' %}
{% load static %}

{% block extra_title %}My Orders{% endblock %}

{% block content %}
<div class="container mt-5">
    {% if request.user.is_authenticated %}
    <h1 class="mb-4">My Orders</h1>
    <div class="row">
        {% if orders %}
        {% for order in orders %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-header">
                    <strong>Order ID:</strong> {{ order.id }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">Order Number: {{ order.order_key }}</h5>
                    <p class="card-text">
                        <strong>Order Date:</strong> {{ order.created }}<br>
                        <strong>Order Total:</strong> {{ order.total_paid }}<br>
                        <strong>Status:</strong> {{ order.status }}
                    </p>
                    <!-- Button to view order details -->
                    <a href="{% url 'orders:order_details' order_number=order.order_key %}" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-12">
            <div class="alert alert-info" role="alert">
                You have no orders yet.
            </div>
        </div>
        {% endif %}
    </div>
    {% else %}
    <h1>Please, log in to see your orders</h1>
    {% endif %}
</div>
{% endblock %}